### PR TITLE
Fix associations with active model serializers

### PR DESCRIPTION
**Pull request by minktom**
Fix active model serializers format with associations (Issue #212)

### CODE REVIEW

**Comment by voltechs** [comment]
Why are none of these pull requests and issues being addressed? Has the author abandoned this? @remiprev?

**Comment by pencil** [comment]
Can't be merged unless it is rebased.

**Comment by voltechs** [comment]
Is it bad etiquette if I fork the repo, make these same changes and submit a (similar) pull request?

**Comment by minktom** [comment]
@pencil, @remiprev: I've rebased the pull request

**Comment by vbalazs** [comment]
ping @pencil

**Comment by oneamtu** [comment]
pong @hubert, whenever you have time

thanks for the fix @minktom!

**Comment by mepatterson** [comment]
ping? is this in a build somewhere I can use? having various problems with AMS and Her integration...

**Comment by hubert** [comment]
i'll take a closer look at this over the weekend.

**Comment by benwoodward** [comment]
Merge pls. :)

**Comment by hubert** [comment]
merged #359, which is this PR rebased with the latest in master. needed to do so in order for it the latest travis checks to be run.

**Comment by benwoodward** [comment]
Awesome! Thanks @hubert

**Pull request closed without merging**
