### PR TITLE
Update RSpec to latest

### PR DESCRIPTION
**Pull request by ticktricktrack**
I've updated the specs to the latest rspec version. Reading them felt a bit painful. I didn't touch anything in 'lib', nor did I make semantic changes to the specs in here. The goal is an update to readability without breaking anything in the process. The big file is just a copy of the default ruby codestyle.

- updated `RSpec` to 3.5
- use ruby 1.9+ hash syntax in specs
- update spec syntax to 3.x using [transpec](https://github.com/yujinakayama/transpec)
- use consistent codestyle throughout the specs using [rubocop](https://github.com/bbatsov/rubocop) ( I went for `"`)

giphy 1

### CODE REVIEW

**Comment by ticktricktrack** [comment]
@edtjones @foxpaul I had some fun cleaning up while skyping. Let's get this repo into a sane state again.

**Comment by edtjones** [comment]
FANTASTIC Rainer. 

Would you like commit access? Feels like you might actually be ahead of us in terms of getting going with this. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by ticktricktrack** [comment]
@edtjones sure, that would be great

**Comment by edtjones** [comment]
Have asked @remiprev to give you access. Thanks for this. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment]
You should have an invite

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Pull request merged**
